### ISSUE TITLE
fails on django 2.0.1

### ISSUE THREAD

**Issue by chfw** [pyexcel-webwares/django-excel#42]
https://travis-ci.org/pyexcel-webwares/django-excel/jobs/327878888

**Comment by ShaheedHaque** [comment]
The issue here is that Django 2.0 makes the on_delete a required argument to ForeignKey(). Thus, this [line](https://github.com/pyexcel-webwares/django-excel/blob/4ac31cb9f46ce0038636479814553c96d2d08d33/polls/models.py#L15) needs to be changed from:


`
    question = models.ForeignKey(Question)
`

to:

`
     question = models.ForeignKey(Question, on_delete=models.CASCADE)
`

For reference, see the [Django 2.0 docs for this example](https://docs.djangoproject.com/en/2.0/intro/tutorial02/#creating-models).

**Comment by chfw** [comment]
still fails with different reason :(, 
https://travis-ci.org/pyexcel-webwares/django-excel/jobs/328829078

**Comment by ShaheedHaque** [comment]
OK, this also seems to be an easy fix. On [this line](https://github.com/pyexcel-webwares/django-excel/blob/4ac31cb9f46ce0038636479814553c96d2d08d33/mysite/urls.py#L6), change this:

`
    url(r'^admin/', include(admin.site.urls)),
`

into this:

`
    url(r'^admin/', admin.site.urls),
`

I'm afraid that being a Django newb, I don't know the history of this change. If this does not fix all the issues, it might be worth regenerating your sample project with a current Django, as it seems that Django 2.0 changed some APIs.

**Comment by chfw** [comment]
Yeah.. I guess something else from existing code will pop up after this one.

**Comment by gabn88** [comment]
Hi @chfw and @ShaheedHaque! Great that you started already on Django 2.0 support.

Could you please tell me if you nee any help on this or that it will be merged soon?

Best regards!

**Comment by ShaheedHaque** [comment]
AFAIK, the code itself works fine under Django 2.0.5. the issue here is to do with the unit tests failing because the sample project used is not updated to current Django APIs.
